"""empty message

Revision ID: 00b9d55cf8ac
Revises: f7b3b4dac6e6
Create Date: 2018-10-27 15:01:20.412885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b9d55cf8ac'
down_revision = 'f7b3b4dac6e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('is_display', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'is_display')
    # ### end Alembic commands ###
