"""empty message

Revision ID: 488d6fbc4ef9
Revises: 00b9d55cf8ac
Create Date: 2018-10-27 15:43:51.242784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488d6fbc4ef9'
down_revision = '00b9d55cf8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlight_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('highlight_comment')
    # ### end Alembic commands ###
