"""empty message

Revision ID: 5986223c8d27
Revises: 488d6fbc4ef9
Create Date: 2018-10-30 10:27:53.259245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5986223c8d27'
down_revision = '488d6fbc4ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('is_display', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', 'is_display')
    # ### end Alembic commands ###
