"""empty message

Revision ID: f0ecd59c5422
Revises: 5993b2ac79fd
Create Date: 2018-10-19 15:55:23.621086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ecd59c5422'
down_revision = '5993b2ac79fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_display', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_display')
    # ### end Alembic commands ###
