"""empty message

Revision ID: f7b3b4dac6e6
Revises: f0ecd59c5422
Create Date: 2018-10-25 14:50:02.906539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b3b4dac6e6'
down_revision = 'f0ecd59c5422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('is_display', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'is_display')
    # ### end Alembic commands ###
